### ISSUE TITLE
Bookdown: Enable PDF Download

### ISSUE THREAD

**Issue by jtelleriar** [m-clark/bayesian-basics#3]
Could PDF download be enabled for the book?

Thank you!
Juan

**Comment by m-clark** [comment]
I'm not sure how well it can be rendered with the customizations for that doc, but I can add the pdf download.  At this point I don't know when I'll get around to it but shouldn't be too long. In the meantime, here is a [link](https://m-clark.github.io/docs/IntroBayes.pdf) to the last pdf version of the document (it started out that way).  It's a couple years older than the web content though.

**Comment by m-clark** [comment]
Going ahead and closing after my latest update, as there just isn't a great way to do pdf and html and I vastly prefer the latter.  However, this looks very nice if you simply print to pdf from the html, so that is what I'd recommend. One will have to do each chapter separately though.  In addition, one can download the epub for an alternative.
